name: Argennos
favicon: null
layout_spectrum: 0.1283051783684641
typography_spectrum: 0.3830215020570904
title: Natural Soaps & Cosmetics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7211854131892323
  lightness: 0.9113068135920912
  saturation: 0.9492836804129183
  rhythmicContrast: 0.7652382946107537
purpose: []
